/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import Dao.Customer;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author hardik
 */
public class Signup extends javax.swing.JFrame {

    Customer user;
    public Signup() {
        this.user = new Customer();
        initComponents();
    }
    boolean checked = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        usernamefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        termscheckbox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        residencefield = new javax.swing.JTextField();
        residencelabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(95, 127, 234));
        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel1.setText("                         User SignUp");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 500, 70));

        namefield.setText("Enter name");
        namefield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        namefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefieldfocuslistener(evt);
            }
        });
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 84, 118, -1));

        usernamefield.setText("Enter username");
        usernamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamefocus(evt);
            }
        });
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 124, 118, -1));

        emailfield.setText("Enter Email");
        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
        });
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 210, 118, -1));

        contactfield.setText("Enter Phone");
        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
        });
        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 257, 120, -1));

        passwordfield.setText("Enter Password");
        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
        });
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 170, 118, -1));

        termscheckbox.setText("Agree to terms and conditions");
        termscheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termscheckboxActionPerformed(evt);
            }
        });
        getContentPane().add(termscheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 337, -1, -1));

        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 379, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 89, -1, -1));

        usernamelabel.setText("UserName");
        getContentPane().add(usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 129, -1, -1));

        emaillabel.setText("Emailid");
        getContentPane().add(emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        contactlabel.setText("PhoneNo");
        getContentPane().add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 262, -1, -1));

        passwordlabel.setText("Password");
        getContentPane().add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 175, -1, -1));

        residencefield.setText("Enter Residence");
        residencefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                residencefieldFocusGained(evt);
            }
        });
        residencefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencefieldActionPerformed(evt);
            }
        });
        getContentPane().add(residencefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 297, 118, -1));

        residencelabel.setText("Residence");
        getContentPane().add(residencelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 302, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/images/signup.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termscheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termscheckboxActionPerformed

        checked = true;
    }//GEN-LAST:event_termscheckboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(checked == false){
            JOptionPane.showMessageDialog(Signup.this,"Please Accept terms and conditions","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if("Enter Name".equals(namefield.getText()) || "".equals(namefield.getText())  )
            JOptionPane.showMessageDialog(null,"Name cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Username".equals(usernamefield.getText())||"".equals(usernamefield.getText()))
            JOptionPane.showMessageDialog(null,"Username cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Password".equals(passwordfield.getPassword())||"".equals(passwordfield.getPassword()))
            JOptionPane.showMessageDialog(null,"Password Invalid" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!emailfield.getText().trim().contains("@"))
            JOptionPane.showMessageDialog(null,"Invalid Email" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!contactfield.getText().trim().matches("[0-9]+") || contactfield.getText().trim().length() < 7)
            JOptionPane.showMessageDialog(null,"Invalid Phone" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Residence".equals(residencefield.getText()) || "".equals(residencefield.getText())  )
            JOptionPane.showMessageDialog(null,"Residence cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            int input;
            input = JOptionPane.showConfirmDialog(Signup.this,"Do you really want to add this user ?","Are you sure?",JOptionPane.YES_NO_OPTION);
            if( input == 0)
            {       
                    int i = user.save();
                    if(i>0){
                            JOptionPane.showMessageDialog(null, "Account Created Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
                            UserLogin.main(new String[]{});
                            dispose();	
                    }
                    else{
                            JOptionPane.showMessageDialog(Signup.this,"Sorry, unable to save!");
                    }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
        String name = namefield.getText(); 
        user.setName(name);
        
    }//GEN-LAST:event_namefieldActionPerformed

    private void namefieldfocuslistener(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefieldfocuslistener
        // TODO add your handling code here:
        if (namefield.getText().equals("Enter name")) {
            namefield.setText("");
            namefield.setForeground(new Color(0,0,45));
            namefield.setFont(new Font("Tahoma", Font.BOLD, 14));
	}
    }//GEN-LAST:event_namefieldfocuslistener

    private void usernamefocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefocus
        // TODO add your handling code here:
        if (usernamefield.getText().equals("Enter username")) {
            usernamefield.setText("");
            usernamefield.setForeground(new Color(0,0,45));
            usernamefield.setFont(new Font("Tahoma", Font.BOLD, 14));
        }
    }//GEN-LAST:event_usernamefocus

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
        user.setUsername(usernamefield.getText());
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
        user.setPassword(String.valueOf(passwordfield.getPassword()));
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
        user.setEmail(emailfield.getText());
    }//GEN-LAST:event_emailfieldActionPerformed

    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
        // TODO add your handling code here:
        user.setContact(contactfield.getText());
    }//GEN-LAST:event_contactfieldActionPerformed

    private void residencefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencefieldActionPerformed
        // TODO add your handling code here:
        user.setResidence(residencefield.getText());
    }//GEN-LAST:event_residencefieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserLogin.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        // TODO add your handling code here:
        String temp = new String(passwordfield.getPassword());
        if(temp.equals("Enter Password"))
              passwordfield.setText("");
    }//GEN-LAST:event_passwordfieldFocusGained

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        // TODO add your handling code here:
        if(emailfield.getText().equals("Enter Email"))
               emailfield.setText("");
    }//GEN-LAST:event_emailfieldFocusGained

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        // TODO add your handling code here:
        if("Enter Phone".equals(contactfield.getText()))
            contactfield.setText("");
    }//GEN-LAST:event_contactfieldFocusGained

    private void residencefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_residencefieldFocusGained
        // TODO add your handling code here:
        if(residencefield.getText().equals("Enter Residence"))
            residencefield.setText("");
    }//GEN-LAST:event_residencefieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField residencefield;
    private javax.swing.JLabel residencelabel;
    private javax.swing.JCheckBox termscheckbox;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
    
     
}
