/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import Dao.Property;
import javax.swing.JOptionPane;

/**
 *
 * @author hardik
 */
public class AddProperty extends javax.swing.JFrame {

    /**
     * Creates new form AddProperty
     */
    Property property = new Property();
    int id;
    public void setid(int id){
        this.id = id;
    }
    public AddProperty() {
        this.id = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namefield = new javax.swing.JTextField();
        locationfield = new javax.swing.JTextField();
        costfield = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        areafield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namefield.setText("Enter Name");
        namefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefieldFocusGained(evt);
            }
        });
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 205, 48));

        locationfield.setText("Enter Location");
        locationfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationfieldFocusGained(evt);
            }
        });
        locationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationfieldActionPerformed(evt);
            }
        });
        getContentPane().add(locationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 205, 46));

        costfield.setText("Enter Cost");
        costfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costfieldFocusGained(evt);
            }
        });
        costfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costfieldActionPerformed(evt);
            }
        });
        getContentPane().add(costfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 205, 49));

        submit.setText("Add Property");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 205, 43));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel2.setText("Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setText("Cost");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 218, -1, 20));

        jLabel4.setText("Rent/Sell");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sell", "Rent" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 205, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 83, 38));

        jLabel7.setText("Area (in sq ft)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setBackground(new java.awt.Color(232, 50, 137));
        jLabel5.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel5.setText("                                Add Property");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 502, 60));

        areafield.setText("Enter Area");
        areafield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areafieldFocusGained(evt);
            }
        });
        areafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areafieldActionPerformed(evt);
            }
        });
        getContentPane().add(areafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 210, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/images/dashboard.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
        property.setName(namefield.getText());
    }//GEN-LAST:event_namefieldActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String s = (String) jComboBox1.getSelectedItem();
        property.setType("Rent".equals(s));

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void locationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationfieldActionPerformed
        // TODO add your handling code here:
        property.setLocation(locationfield.getText());
    }//GEN-LAST:event_locationfieldActionPerformed

    private void costfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costfieldActionPerformed
        // TODO add your handling code here:
        property.setCost(Integer.parseInt(costfield.getText()));
    }//GEN-LAST:event_costfieldActionPerformed
     
    // Checks for invalid inputs and saves a property into database
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        if("Enter Name".equals(namefield.getText()) || "".equals(namefield.getText())  )
            JOptionPane.showMessageDialog(null,"Name cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Location".equals(locationfield.getText())||"".equals(locationfield.getText()))
            JOptionPane.showMessageDialog(null,"Location cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!costfield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Cost","ERROR", JOptionPane.ERROR_MESSAGE);  
        else if(!areafield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Area","ERROR", JOptionPane.ERROR_MESSAGE);  
        else{
            property.setOwnerid(id);
            int save = property.save();
            if(save>0)
                JOptionPane.showMessageDialog(null, "Property Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            else{
                JOptionPane.showMessageDialog(null, "Unable to save Add your Property", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserDashboard u1 =  new UserDashboard();
        u1.setid(this.id);
        u1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefieldFocusGained
        // TODO add your handling code here:
        if(namefield.getText().equals("Enter Name"))
            namefield.setText("");
    }//GEN-LAST:event_namefieldFocusGained

    private void locationfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationfieldFocusGained
        // TODO add your handling code here:
        if(locationfield.getText().equals("Enter Location"))
            locationfield.setText("");
    }//GEN-LAST:event_locationfieldFocusGained

    private void costfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costfieldFocusGained
        // TODO add your handling code here:
        if(costfield.getText().equals("Enter Cost"))
            costfield.setText("");
    }//GEN-LAST:event_costfieldFocusGained

    private void areafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areafieldActionPerformed
        // TODO add your handling code here:
        int temparea = Integer.parseInt(areafield.getText());
        property.setArea(temparea);
    }//GEN-LAST:event_areafieldActionPerformed
    
    private void areafieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areafieldFocusGained

        if(areafield.getText().equals("Enter Area"))
            areafield.setText("");
    }//GEN-LAST:event_areafieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddProperty().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areafield;
    private javax.swing.JTextField costfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField locationfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
